jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8090
   servlet:
      context-path: /ceiba-odontologia
      session:
         timeout: 21600s

#spring:
#   datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#      jdbcUrl: jdbc:mysql://mysql_container/ceiba-odontologia?useSSL=false
#      username: root
#      password: secret
#      hikari:
#         poolName: pool


spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/ceiba-odontologia
      username: root
      password: Colombia12
      hikari:
         poolName: pool


#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    driver-class-name: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    jdbcUrl: jdbc:h2:mem:ceiba-odontologia;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    username: sa
#    password:
#    hikari:
#       poolName: pool

    

